"""rename department

Revision ID: 94262d34c280
Revises: 1a7d34dac58e
Create Date: 2024-06-29 00:08:36.432199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94262d34c280'
down_revision = '1a7d34dac58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'location',  new_column_name='address')
